name = "PyYAXArrays"
uuid = "a3bebb63-7b3d-412a-a2c3-cb39e498b6da"
authors = ["Fabian Gans <fgans@bgc-jena.mpg.de> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
